from beam import Manifold

data = """\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""


def test_puzzle_one():
    result = Manifold(data.splitlines())
    assert result.splits == 21

def test_puzzle_two():
    result = Manifold(data.splitlines())
    assert result.timelines == 40
